### ISSUE TITLE
nunjucks 在解析markdown中的数学公式时有意外表现

### ISSUE THREAD

**Issue by hooozen** [hexojs/hexo-renderer-nunjucks#25]
When I write a math equation in my markdown file like following
```md
Indicator Function, $I_{\{0<x<1\}}$
```
It is expected to be shown as 
<img width="265" alt="image" src="https://github.com/hexojs/hexo-renderer-nunjucks/assets/24765496/250ccb01-30a7-4865-bd04-16e5e13cd00e">

But after hexo-renderer-nunjucks process it become 
```html
Indicator Function, $I_{{0&lt;x&lt;1}}$
```
then it will renderer by latex engine like
<img width="265" alt="image" src="https://github.com/hexojs/hexo-renderer-nunjucks/assets/24765496/9800b736-799a-4e24-b356-b80859cba586">
which missing `{}`.

Plugin behave differently from the standard. So it may be considered to process latex equation in `$...$` or `$$...$` specially.

**Comment by stevenjoezhang** [comment]
You can add a space between `{{`, or

See https://github.com/hexojs/hexo/pull/4518

**Comment by hooozen** [comment]
thank you very much.  I also solved the problem well by using the markdown renderer hexo-renderer-pandoc  replacing hexo-renderer-marked.
